name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 # Updated to v2 which is the latest stable at the time of my last update
    - name: Run Makefile
      run: |
        cd SerializeDat
        make
